%% Experiment S6: Parameter sensitivity of RSI-OLSTEC
% Paired one-factor-at-a-time sensitivity analysis under a common
% synthetic tracking scenario with impulsive corruption and one abrupt
% structural mutation.
clear; clc; close all;

repo_root = fileparts(mfilename('fullpath'));
addpath(repo_root);
addpath(genpath(fullfile(repo_root, 'tool')));
addpath(genpath(fullfile(repo_root, 'auxiliary')));
addpath(genpath(fullfile(repo_root, 'benchmark')));

%% 1. Experimental configuration
num_trials = 50;
trial_seed_ids = (2001:(2000 + num_trials))';

data_settings = struct( ...
    'tensor_dims', [50, 50, 500], ...
    'true_rank', 5, ...
    'transition_boundary', 251, ...
    'mutation_scale', 0.50, ...
    'snr_db', 25, ...
    'spatter_density', 0.05, ...
    'spatter_base_magnitude', 0.50, ...
    'observation_ratio', 0.50, ...
    'side_baseline', 10.0, ...
    'side_event_gain', 10.0, ...
    'side_event_decay', 0.80, ...
    'side_noise_sigma', 0.20, ...
    'side_delay_range', [2, 5], ...
    'burn_in_frames', 30, ...
    'huber_delta_lower_bound', 0.01, ...
    'side_threshold_floor', 0.05);

default_config = struct( ...
    'id', 'default', ...
    'label', 'Default', ...
    'parameter_family', 'default', ...
    'parameter_value', NaN, ...
    'lambda_min', 0.70, ...
    'lambda_max', 0.80, ...
    'huber_scale_multiplier', 3.0, ...
    'grad_ema_alpha', 0.999, ...
    'side_threshold_multiplier', 3.0, ...
    'mu', 0.01, ...
    'estimated_rank', 5, ...
    'irls_max_iters', 3);

parameter_values = struct( ...
    'lambda_min', [0.10, 0.40, 0.70], ...
    'lambda_max', [0.80, 0.90, 0.99], ...
    'huber_scale_multiplier', [1.345, 3.0, 6.0], ...
    'grad_ema_alpha', [0.90, 0.99, 0.999], ...
    'side_threshold_multiplier', [1.0, 3.0, 6.0], ...
    'mu', [1e-3, 1e-2, 1e-1], ...
    'estimated_rank', [3, 5, 7], ...
    'irls_max_iters', [1, 3, 5]);

configurations = define_s6_configurations( ...
    default_config, parameter_values);
num_configurations = numel(configurations);
max_estimated_rank = max([configurations.estimated_rank]);

irls_tolerance = 1e-3;
normalization_epsilon = 1e-3;
ci_level = 0.95;
bootstrap_resamples = 10000;
export_results = true;

metric_names = { ...
    'PreMutationMeanNRE50', ...
    'RecoveryIntegral50', ...
    'FinalMeanNRE100', ...
    'MeanLambda', ...
    'MinimumLambdaPost50', ...
    'MeanPriorIRLSIterations', ...
    'MeanPosteriorIRLSIterations'};

result_dir = fullfile(repo_root, 'result', 'S6');
checkpoint_file = fullfile(result_dir, 'S6_checkpoint.mat');
if export_results && ~exist(result_dir, 'dir')
    mkdir(result_dir);
end

settings = struct( ...
    'num_trials', num_trials, ...
    'trial_seed_ids', trial_seed_ids, ...
    'data', data_settings, ...
    'default_config', default_config, ...
    'parameter_values', parameter_values, ...
    'configurations', configurations, ...
    'irls_tolerance', irls_tolerance, ...
    'normalization_epsilon', normalization_epsilon, ...
    'ci_level', ci_level, ...
    'bootstrap_resamples', bootstrap_resamples);

%% 2. Result storage and checkpoint
total_frames = data_settings.tensor_dims(3);
num_metrics = numel(metric_names);

state.completed_trials = false(num_trials, 1);
state.status = zeros(num_configurations, num_trials, 'uint8');
state.metrics = NaN(num_configurations, num_trials, num_metrics);
state.runtime_seconds = NaN(num_configurations, num_trials);
state.nre_curves = NaN(num_configurations, num_trials, total_frames);
state.lambda_curves = NaN(num_configurations, num_trials, total_frames);
state.huber_delta = NaN(num_configurations, num_trials);
state.side_threshold = NaN(num_configurations, num_trials);
state.visual_sigma = NaN(num_trials, 1);
state.side_sigma = NaN(num_trials, 1);
state.actual_observation_ratio = NaN(num_trials, 1);
state.actual_spatter_density = NaN(num_trials, 1);
state.side_delay = NaN(num_trials, 1);
state.execution_position = NaN(num_configurations, num_trials);
state.failure_records = struct( ...
    'Trial', {}, 'TrialSeed', {}, 'ConfigurationID', {}, ...
    'Identifier', {}, 'Message', {});

if exist(checkpoint_file, 'file')
    loaded = load(checkpoint_file, 'checkpoint');
    if ~isfield(loaded, 'checkpoint') || ...
            ~isequaln(loaded.checkpoint.settings, settings)
        error('Exp_S6:CheckpointMismatch', ...
            'The existing S6 checkpoint uses different settings.');
    end
    state = loaded.checkpoint.state;
    fprintf('Resuming S6 from %d/%d completed trials.\n', ...
        nnz(state.completed_trials), num_trials);
end

%% 3. Paired Monte Carlo sensitivity analysis
fprintf(['Starting S6 with %d paired trials and %d unique parameter ', ...
    'configurations per trial.\n'], num_trials, num_configurations);

for trial = 1:num_trials
    if state.completed_trials(trial)
        continue;
    end

    trial_seed = trial_seed_ids(trial);
    fprintf('Trial %d/%d (seed %d)\n', trial, num_trials, trial_seed);

    seeds = make_s6_seeds(trial_seed);
    trial_data = generate_s6_trial( ...
        data_settings, seeds, max_estimated_rank);

    state.visual_sigma(trial) = trial_data.visual_sigma;
    state.side_sigma(trial) = trial_data.side_sigma;
    state.actual_observation_ratio(trial) = ...
        nnz(trial_data.observation_mask) / ...
        numel(trial_data.observation_mask);
    state.actual_spatter_density(trial) = ...
        trial_data.actual_spatter_density;
    state.side_delay(trial) = trial_data.side_delay;

    execution_stream = RandStream( ...
        'mt19937ar', 'Seed', seeds.execution_order);
    [~, execution_order] = sort( ...
        rand(execution_stream, num_configurations, 1));

    for execution_position = 1:num_configurations
        configuration_index = execution_order(execution_position);
        configuration = configurations(configuration_index);
        state.execution_position(configuration_index, trial) = ...
            execution_position;

        huber_delta = max( ...
            data_settings.huber_delta_lower_bound, ...
            configuration.huber_scale_multiplier * ...
            trial_data.visual_sigma);
        side_threshold = max( ...
            data_settings.side_threshold_floor, ...
            configuration.side_threshold_multiplier * sqrt(2) * ...
            trial_data.side_sigma);
        state.huber_delta(configuration_index, trial) = huber_delta;
        state.side_threshold(configuration_index, trial) = ...
            side_threshold;

        rank_r = configuration.estimated_rank;
        initialization = struct( ...
            'A', trial_data.initialization.A(:, 1:rank_r), ...
            'B', trial_data.initialization.B(:, 1:rank_r), ...
            'C', trial_data.initialization.C(:, 1:rank_r));

        try
            [nre_curve, lambda_curve, metrics, elapsed] = ...
                run_s6_configuration(trial_data, configuration, ...
                initialization, huber_delta, side_threshold, ...
                irls_tolerance, normalization_epsilon, metric_names, ...
                trial);

            state.status(configuration_index, trial) = uint8(1);
            state.metrics(configuration_index, trial, :) = ...
                reshape(metrics, 1, 1, []);
            state.runtime_seconds(configuration_index, trial) = elapsed;
            state.nre_curves(configuration_index, trial, :) = ...
                reshape(nre_curve, 1, 1, []);
            state.lambda_curves(configuration_index, trial, :) = ...
                reshape(lambda_curve, 1, 1, []);

            fprintf('  %-24s %8.2f s\n', ...
                configuration.id, elapsed);
        catch exception
            if is_process_interruption(exception)
                rethrow(exception);
            end

            state.status(configuration_index, trial) = uint8(2);
            state.failure_records(end + 1) = make_failure_record( ...
                trial, trial_seed, configuration.id, exception);
            fprintf('  %-24s failed: %s\n', ...
                configuration.id, exception.message);
        end
    end

    state.completed_trials(trial) = true;
    if export_results
        checkpoint = struct('settings', settings, 'state', state);
        save_checkpoint_atomic(checkpoint_file, checkpoint);
        clear checkpoint;
    end
    clear trial_data;
end

%% 4. Statistical summaries
[per_trial_table, summary_table] = build_s6_tables( ...
    state, configurations, metric_names, trial_seed_ids, ...
    ci_level, bootstrap_resamples);
failure_table = build_failure_table(state.failure_records);

fprintf('\nS6 parameter-sensitivity summary\n');
fprintf('%-24s %8s %14s %14s\n', ...
    'Configuration', 'Valid', 'Final NRE', 'Recovery');
for configuration_index = 1:num_configurations
    fprintf('%-24s %8d %14.4f %14.4f\n', ...
        configurations(configuration_index).id, ...
        summary_table.SuccessfulRuns(configuration_index), ...
        summary_table.FinalMeanNRE100Mean(configuration_index), ...
        summary_table.RecoveryIntegral50Mean(configuration_index));
end

if export_results
    writetable(per_trial_table, ...
        fullfile(result_dir, 'S6_per_trial_metrics.csv'));
    writetable(summary_table, ...
        fullfile(result_dir, 'S6_summary_statistics.csv'));
    writetable(failure_table, ...
        fullfile(result_dir, 'S6_failure_log.csv'));
    save(fullfile(result_dir, 'S6_stats.mat'), ...
        'settings', 'configurations', 'metric_names', 'state', ...
        'per_trial_table', 'summary_table', 'failure_table', '-v7');
end

%% 5. Figures
plot_s6_metric(summary_table, configurations, ...
    'FinalMeanNRE100', 'Final mean NRE over 100 frames', ...
    'S6_final_nre_sensitivity', result_dir, export_results);
plot_s6_metric(summary_table, configurations, ...
    'RecoveryIntegral50', 'Recovery integral over 50 frames', ...
    'S6_recovery_sensitivity', result_dir, export_results);

fprintf('S6 outputs written to: %s\n', result_dir);

%% Local functions
function configurations = define_s6_configurations( ...
    default_config, parameter_values)

    expected_count = 17;
    configurations = repmat(default_config, expected_count, 1);
    configuration_count = 1;
    specifications = { ...
        'lambda_min', 'lambda_min', 'Lambda min'; ...
        'lambda_max', 'lambda_max', 'Lambda max'; ...
        'huber', 'huber_scale_multiplier', 'Huber multiplier'; ...
        'alpha', 'grad_ema_alpha', 'Alpha'; ...
        'theta', 'side_threshold_multiplier', 'Theta multiplier'; ...
        'mu', 'mu', 'Mu'; ...
        'rank', 'estimated_rank', 'Estimated rank'; ...
        'irls', 'irls_max_iters', 'IRLS iterations'};

    for specification_index = 1:size(specifications, 1)
        family = specifications{specification_index, 1};
        field = specifications{specification_index, 2};
        label_prefix = specifications{specification_index, 3};
        values = parameter_values.(field);
        default_value = default_config.(field);

        for value_index = 1:numel(values)
            value = values(value_index);
            if abs(value - default_value) <= ...
                    10 * eps(max(1, abs(default_value)))
                continue;
            end
            id = [family, '_', numeric_identifier(value)];
            label = sprintf('%s %.4g', label_prefix, value);
            configuration_count = configuration_count + 1;
            configurations(configuration_count) = changed_configuration( ...
                default_config, id, label, family, value, field, value);
        end
    end

    configurations = configurations(1:configuration_count);
    configuration_ids = {configurations.id};
    if numel(configurations) ~= expected_count || ...
            numel(unique(configuration_ids)) ~= numel(configurations)
        error('Exp_S6:InvalidConfigurationSet', ...
            'S6 must contain 17 unique parameter configurations.');
    end
end

function identifier = numeric_identifier(value)
    identifier = sprintf('%.4g', value);
    identifier = strrep(identifier, '-', 'm');
    identifier = strrep(identifier, '+', '');
    identifier = strrep(identifier, '.', 'p');
end

function configuration = changed_configuration( ...
    default_config, id, label, family, parameter_value, field, value)

    configuration = default_config;
    configuration.id = id;
    configuration.label = label;
    configuration.parameter_family = family;
    configuration.parameter_value = parameter_value;
    configuration.(field) = value;
end

function seeds = make_s6_seeds(trial_seed)
    seeds.subspace = 100000 + trial_seed;
    seeds.temporal = 200000 + trial_seed;
    seeds.gaussian = 300000 + trial_seed;
    seeds.spatter = 400000 + trial_seed;
    seeds.observation = 500000 + trial_seed;
    seeds.side_delay = 600000 + trial_seed;
    seeds.side_noise = 700000 + trial_seed;
    seeds.initialization = 800000 + trial_seed;
    seeds.execution_order = 900000 + trial_seed;
end

function trial_data = generate_s6_trial( ...
    settings, seeds, max_estimated_rank)

    rows = settings.tensor_dims(1);
    cols = settings.tensor_dims(2);
    total_frames = settings.tensor_dims(3);
    true_rank = settings.true_rank;

    stream = RandStream('mt19937ar', 'Seed', seeds.subspace);
    basis_a_before = orthonormalize_with_sign( ...
        randn(stream, rows, true_rank));
    basis_b_before = orthonormalize_with_sign( ...
        randn(stream, cols, true_rank));
    basis_a_after = orthonormalize_with_sign( ...
        basis_a_before + settings.mutation_scale * ...
        randn(stream, rows, true_rank));
    basis_b_after = orthonormalize_with_sign( ...
        basis_b_before + settings.mutation_scale * ...
        randn(stream, cols, true_rank));

    stream = RandStream('mt19937ar', 'Seed', seeds.temporal);
    frame_axis = (1:total_frames)';
    temporal_coefficients = zeros(total_frames, true_rank);
    for component = 1:true_rank
        temporal_coefficients(:, component) = 10.0 + ...
            2.0 * sin(2 * pi * frame_axis / ...
            (100 + 10 * component)) + ...
            0.1 * randn(stream, total_frames, 1);
    end

    clean_tensor = zeros(rows, cols, total_frames);
    for frame = 1:total_frames
        if frame < settings.transition_boundary
            basis_a = basis_a_before;
            basis_b = basis_b_before;
        else
            basis_a = basis_a_after;
            basis_b = basis_b_after;
        end
        clean_tensor(:, :, frame) = basis_a * ...
            diag(temporal_coefficients(frame, :)) * basis_b';
    end

    signal_power = norm(clean_tensor(:))^2 / numel(clean_tensor);
    gaussian_sigma = sqrt( ...
        signal_power / 10^(settings.snr_db / 10));
    stream = RandStream('mt19937ar', 'Seed', seeds.gaussian);
    observed_full = clean_tensor + gaussian_sigma * ...
        randn(stream, rows, cols, total_frames);

    stream = RandStream('mt19937ar', 'Seed', seeds.spatter);
    spatter_mask = rand(stream, rows, cols, total_frames) < ...
        settings.spatter_density;
    num_spatter = nnz(spatter_mask);
    observed_full(spatter_mask) = observed_full(spatter_mask) + ...
        settings.spatter_base_magnitude * ...
        (1 + abs(randn(stream, num_spatter, 1)));

    stream = RandStream('mt19937ar', 'Seed', seeds.observation);
    observation_mask = rand(stream, rows, cols, total_frames) < ...
        settings.observation_ratio;
    observed_tensor = observed_full .* observation_mask;

    stream = RandStream('mt19937ar', 'Seed', seeds.side_delay);
    side_delay = randi(stream, settings.side_delay_range, 1, 1);
    side_event_start = settings.transition_boundary + side_delay;
    side_event = zeros(total_frames, 1);
    side_event(side_event_start) = ...
        settings.side_event_gain * settings.mutation_scale;
    for frame = side_event_start + 1:total_frames
        side_event(frame) = settings.side_event_decay * ...
            side_event(frame - 1);
    end
    stream = RandStream('mt19937ar', 'Seed', seeds.side_noise);
    side_signal = settings.side_baseline + side_event + ...
        settings.side_noise_sigma * ...
        randn(stream, total_frames, 1);

    stream = RandStream('mt19937ar', 'Seed', seeds.initialization);
    initialization.A = orthonormalize_with_sign( ...
        randn(stream, rows, max_estimated_rank));
    initialization.B = orthonormalize_with_sign( ...
        randn(stream, cols, max_estimated_rank));
    initialization.C = randn( ...
        stream, total_frames, max_estimated_rank);

    visual_sigma = estimate_visual_sigma( ...
        observed_tensor, observation_mask, settings.burn_in_frames);
    side_sigma = estimate_side_sigma( ...
        side_signal, settings.burn_in_frames);

    trial_data.clean_tensor = clean_tensor;
    trial_data.observed_tensor = observed_tensor;
    trial_data.observation_mask = observation_mask;
    trial_data.side_signal = side_signal;
    trial_data.initialization = initialization;
    trial_data.visual_sigma = visual_sigma;
    trial_data.side_sigma = side_sigma;
    trial_data.side_delay = side_delay;
    trial_data.actual_spatter_density = ...
        num_spatter / numel(spatter_mask);
    trial_data.transition_boundary = settings.transition_boundary;
end

function basis = orthonormalize_with_sign(input_matrix)
    [q_matrix, r_matrix] = qr(input_matrix, 0);
    signs = sign(diag(r_matrix) + 1e-10);
    basis = q_matrix * diag(signs);
end

function sigma = estimate_visual_sigma( ...
    observed_tensor, observation_mask, burn_in_frames)

    differences = cell(burn_in_frames - 1, 1);
    for frame = 2:burn_in_frames
        common_mask = observation_mask(:, :, frame) & ...
            observation_mask(:, :, frame - 1);
        frame_difference = observed_tensor(:, :, frame) - ...
            observed_tensor(:, :, frame - 1);
        differences{frame - 1} = frame_difference(common_mask);
    end
    differences = vertcat(differences{:});
    if isempty(differences)
        error('Exp_S6:UnavailableVisualScale', ...
            'No common observed pixels are available during burn-in.');
    end

    center = median(differences);
    mad_value = median(abs(differences - center));
    sigma = (1.4826 * mad_value) / sqrt(2);
    if ~isfinite(sigma) || sigma <= 0
        error('Exp_S6:InvalidVisualScale', ...
            'The burn-in visual scale estimate is not positive and finite.');
    end
end

function sigma = estimate_side_sigma(side_signal, burn_in_frames)
    differences = diff(side_signal(1:burn_in_frames));
    center = median(differences);
    mad_value = median(abs(differences - center));
    sigma = (1.4826 * mad_value) / sqrt(2);
    if ~isfinite(sigma) || sigma <= 0
        error('Exp_S6:InvalidSideScale', ...
            'The burn-in side-information scale is not positive and finite.');
    end
end

function [nre_curve, lambda_curve, metrics, elapsed] = ...
    run_s6_configuration(trial_data, configuration, initialization, ...
    huber_delta, side_threshold, irls_tolerance, ...
    normalization_epsilon, metric_names, trial)

    tensor_dims = size(trial_data.clean_tensor);
    options = struct( ...
        'lambda_min', configuration.lambda_min, ...
        'lambda_max', configuration.lambda_max, ...
        'huber_delta', huber_delta, ...
        'min_grad_threshold', side_threshold, ...
        'mu', configuration.mu, ...
        'grad_ema_alpha', configuration.grad_ema_alpha, ...
        'irls_max_iters', configuration.irls_max_iters, ...
        'irls_tolerance', irls_tolerance, ...
        'normalization_epsilon', normalization_epsilon, ...
        'verbose', 0, ...
        'early_stop_on', 'none', ...
        'store_matrix', true, ...
        'store_subinfo', false);

    timer = tic;
    [~, ~, information] = rsi_olstec( ...
        trial_data.observed_tensor, trial_data.observation_mask, [], ...
        tensor_dims, configuration.estimated_rank, initialization, ...
        options, trial_data.side_signal);
    elapsed = toc(timer);

    nre_curve = validate_complete_nre( ...
        compute_true_nre_tensor( ...
        trial_data.clean_tensor, information.L), ...
        tensor_dims(3), configuration.id, trial);
    nre_curve = nre_curve(:)';

    lambda_curve = information.lambda_history(:)';
    if numel(lambda_curve) ~= tensor_dims(3) || ...
            any(~isfinite(lambda_curve))
        error('Exp_S6:InvalidLambdaHistory', ...
            'The forgetting-factor history is incomplete or non-finite.');
    end
    tolerance = 1e-12;
    if any(lambda_curve < configuration.lambda_min - tolerance) || ...
            any(lambda_curve > configuration.lambda_max + tolerance)
        error('Exp_S6:InvalidLambdaHistory', ...
            'The forgetting factor lies outside its configured bounds.');
    end

    prior_iterations = information.prior_irls_iterations(:);
    posterior_iterations = information.posterior_irls_iterations(:);
    if numel(prior_iterations) ~= tensor_dims(3) || ...
            numel(posterior_iterations) ~= tensor_dims(3) || ...
            any(~isfinite(prior_iterations)) || ...
            any(~isfinite(posterior_iterations))
        error('Exp_S6:InvalidIRLSHistory', ...
            'The IRLS iteration histories are incomplete or non-finite.');
    end

    metrics = compute_s6_metrics( ...
        nre_curve, lambda_curve, prior_iterations, ...
        posterior_iterations, trial_data.transition_boundary);
    if numel(metrics) ~= numel(metric_names) || any(~isfinite(metrics))
        error('Exp_S6:InvalidMetrics', ...
            'The parameter-sensitivity metrics are incomplete or non-finite.');
    end
end

function metrics = compute_s6_metrics( ...
    nre_curve, lambda_curve, prior_iterations, ...
    posterior_iterations, transition_boundary)

    total_frames = numel(nre_curve);
    pre_50 = (transition_boundary - 50):(transition_boundary - 1);
    post_50 = transition_boundary:(transition_boundary + 49);
    final_100 = (total_frames - 99):total_frames;

    metrics = [ ...
        mean(nre_curve(pre_50)), ...
        sum(nre_curve(post_50)), ...
        mean(nre_curve(final_100)), ...
        mean(lambda_curve), ...
        min(lambda_curve(post_50)), ...
        mean(prior_iterations), ...
        mean(posterior_iterations)];
end

function record = make_failure_record( ...
    trial, trial_seed, configuration_id, exception)

    identifier = exception.identifier;
    if isempty(identifier)
        identifier = 'unidentified_exception';
    end
    message_text = regexprep( ...
        strtrim(exception.message), '[\r\n]+', ' | ');
    record = struct( ...
        'Trial', trial, ...
        'TrialSeed', trial_seed, ...
        'ConfigurationID', configuration_id, ...
        'Identifier', identifier, ...
        'Message', message_text);
end

function value = is_process_interruption(exception)
    diagnostic_text = lower([exception.identifier, ' ', exception.message]);
    value = contains(diagnostic_text, 'operationterminatedbyuser') || ...
        contains(diagnostic_text, 'terminated by user') || ...
        contains(diagnostic_text, 'operation terminated') || ...
        contains(diagnostic_text, 'nomem') || ...
        contains(diagnostic_text, 'outofmemory') || ...
        contains(diagnostic_text, 'out of memory') || ...
        contains(diagnostic_text, 'memory allocation') || ...
        contains(diagnostic_text, 'requested array exceeds') || ...
        contains(diagnostic_text, 'unable to allocate');
end

function [per_trial_table, summary_table] = build_s6_tables( ...
    state, configurations, metric_names, trial_seed_ids, ...
    ci_level, bootstrap_resamples)

    num_configurations = numel(configurations);
    num_trials = numel(trial_seed_ids);
    num_rows = num_configurations * num_trials;
    metric_index = @(name) find(strcmp(metric_names, name), 1);

    Trial = zeros(num_rows, 1);
    TrialSeed = zeros(num_rows, 1);
    ConfigurationID = cell(num_rows, 1);
    ParameterFamily = cell(num_rows, 1);
    ParameterValue = NaN(num_rows, 1);
    LambdaMin = NaN(num_rows, 1);
    LambdaMax = NaN(num_rows, 1);
    HuberScaleMultiplier = NaN(num_rows, 1);
    HuberDelta = NaN(num_rows, 1);
    Alpha = NaN(num_rows, 1);
    SideThresholdMultiplier = NaN(num_rows, 1);
    SideThreshold = NaN(num_rows, 1);
    Mu = NaN(num_rows, 1);
    EstimatedRank = NaN(num_rows, 1);
    IRLSMaxIterations = NaN(num_rows, 1);
    Status = zeros(num_rows, 1, 'uint8');
    ExecutionPosition = NaN(num_rows, 1);
    RuntimeSeconds = NaN(num_rows, 1);
    PreMutationMeanNRE50 = NaN(num_rows, 1);
    RecoveryIntegral50 = NaN(num_rows, 1);
    FinalMeanNRE100 = NaN(num_rows, 1);
    MeanLambda = NaN(num_rows, 1);
    MinimumLambdaPost50 = NaN(num_rows, 1);
    MeanPriorIRLSIterations = NaN(num_rows, 1);
    MeanPosteriorIRLSIterations = NaN(num_rows, 1);
    VisualSigma = NaN(num_rows, 1);
    SideSigma = NaN(num_rows, 1);
    ActualObservationRatio = NaN(num_rows, 1);
    ActualSpatterDensity = NaN(num_rows, 1);
    SideDelay = NaN(num_rows, 1);

    row = 0;
    for trial = 1:num_trials
        for configuration_index = 1:num_configurations
            row = row + 1;
            configuration = configurations(configuration_index);
            Trial(row) = trial;
            TrialSeed(row) = trial_seed_ids(trial);
            ConfigurationID{row} = configuration.id;
            ParameterFamily{row} = configuration.parameter_family;
            ParameterValue(row) = configuration.parameter_value;
            LambdaMin(row) = configuration.lambda_min;
            LambdaMax(row) = configuration.lambda_max;
            HuberScaleMultiplier(row) = ...
                configuration.huber_scale_multiplier;
            HuberDelta(row) = ...
                state.huber_delta(configuration_index, trial);
            Alpha(row) = configuration.grad_ema_alpha;
            SideThresholdMultiplier(row) = ...
                configuration.side_threshold_multiplier;
            SideThreshold(row) = ...
                state.side_threshold(configuration_index, trial);
            Mu(row) = configuration.mu;
            EstimatedRank(row) = configuration.estimated_rank;
            IRLSMaxIterations(row) = configuration.irls_max_iters;
            Status(row) = state.status(configuration_index, trial);
            ExecutionPosition(row) = ...
                state.execution_position(configuration_index, trial);
            RuntimeSeconds(row) = ...
                state.runtime_seconds(configuration_index, trial);
            PreMutationMeanNRE50(row) = state.metrics( ...
                configuration_index, trial, ...
                metric_index('PreMutationMeanNRE50'));
            RecoveryIntegral50(row) = state.metrics( ...
                configuration_index, trial, ...
                metric_index('RecoveryIntegral50'));
            FinalMeanNRE100(row) = state.metrics( ...
                configuration_index, trial, ...
                metric_index('FinalMeanNRE100'));
            MeanLambda(row) = state.metrics( ...
                configuration_index, trial, ...
                metric_index('MeanLambda'));
            MinimumLambdaPost50(row) = state.metrics( ...
                configuration_index, trial, ...
                metric_index('MinimumLambdaPost50'));
            MeanPriorIRLSIterations(row) = state.metrics( ...
                configuration_index, trial, ...
                metric_index('MeanPriorIRLSIterations'));
            MeanPosteriorIRLSIterations(row) = state.metrics( ...
                configuration_index, trial, ...
                metric_index('MeanPosteriorIRLSIterations'));
            VisualSigma(row) = state.visual_sigma(trial);
            SideSigma(row) = state.side_sigma(trial);
            ActualObservationRatio(row) = ...
                state.actual_observation_ratio(trial);
            ActualSpatterDensity(row) = ...
                state.actual_spatter_density(trial);
            SideDelay(row) = state.side_delay(trial);
        end
    end

    per_trial_table = table( ...
        Trial, TrialSeed, ConfigurationID, ParameterFamily, ...
        ParameterValue, LambdaMin, LambdaMax, ...
        HuberScaleMultiplier, HuberDelta, Alpha, ...
        SideThresholdMultiplier, SideThreshold, Mu, EstimatedRank, ...
        IRLSMaxIterations, Status, ExecutionPosition, RuntimeSeconds, ...
        PreMutationMeanNRE50, RecoveryIntegral50, FinalMeanNRE100, ...
        MeanLambda, MinimumLambdaPost50, MeanPriorIRLSIterations, ...
        MeanPosteriorIRLSIterations, VisualSigma, SideSigma, ...
        ActualObservationRatio, ActualSpatterDensity, SideDelay);

    ConfigurationID = {configurations.id}';
    Label = {configurations.label}';
    ParameterFamily = {configurations.parameter_family}';
    ParameterValue = [configurations.parameter_value]';
    SuccessfulRuns = zeros(num_configurations, 1);
    FailedRuns = zeros(num_configurations, 1);
    PairedRuns = zeros(num_configurations, 1);

    PreMutationMeanNRE50Mean = NaN(num_configurations, 1);
    RecoveryIntegral50Mean = NaN(num_configurations, 1);
    RecoveryIntegral50Std = NaN(num_configurations, 1);
    RecoveryIntegral50CILower = NaN(num_configurations, 1);
    RecoveryIntegral50CIUpper = NaN(num_configurations, 1);
    RecoveryIntegral50DifferenceMean = NaN(num_configurations, 1);
    RecoveryIntegral50DifferenceCILower = NaN(num_configurations, 1);
    RecoveryIntegral50DifferenceCIUpper = NaN(num_configurations, 1);
    FinalMeanNRE100Mean = NaN(num_configurations, 1);
    FinalMeanNRE100Std = NaN(num_configurations, 1);
    FinalMeanNRE100CILower = NaN(num_configurations, 1);
    FinalMeanNRE100CIUpper = NaN(num_configurations, 1);
    FinalMeanNRE100DifferenceMean = NaN(num_configurations, 1);
    FinalMeanNRE100DifferenceCILower = NaN(num_configurations, 1);
    FinalMeanNRE100DifferenceCIUpper = NaN(num_configurations, 1);
    RuntimeMedianSeconds = NaN(num_configurations, 1);
    RuntimeIQRSeconds = NaN(num_configurations, 1);
    MeanLambdaMean = NaN(num_configurations, 1);
    MinimumLambdaPost50Mean = NaN(num_configurations, 1);
    MeanPriorIRLSIterationsMean = NaN(num_configurations, 1);
    MeanPosteriorIRLSIterationsMean = NaN(num_configurations, 1);
    HuberDeltaMean = NaN(num_configurations, 1);
    SideThresholdMean = NaN(num_configurations, 1);

    recovery_index = metric_index('RecoveryIntegral50');
    final_index = metric_index('FinalMeanNRE100');
    default_recovery = reshape( ...
        state.metrics(1, :, recovery_index), [], 1);
    default_final = reshape( ...
        state.metrics(1, :, final_index), [], 1);
    default_valid = state.status(1, :)' == 1;

    for configuration_index = 1:num_configurations
        valid = state.status(configuration_index, :)' == 1;
        SuccessfulRuns(configuration_index) = nnz(valid);
        FailedRuns(configuration_index) = nnz( ...
            state.status(configuration_index, :)' == 2);

        pre_values = reshape(state.metrics( ...
            configuration_index, :, ...
            metric_index('PreMutationMeanNRE50')), [], 1);
        recovery_values = reshape(state.metrics( ...
            configuration_index, :, recovery_index), [], 1);
        final_values = reshape(state.metrics( ...
            configuration_index, :, final_index), [], 1);

        PreMutationMeanNRE50Mean(configuration_index) = ...
            finite_mean(pre_values(valid));
        [RecoveryIntegral50Mean(configuration_index), ...
            RecoveryIntegral50Std(configuration_index), ...
            RecoveryIntegral50CILower(configuration_index), ...
            RecoveryIntegral50CIUpper(configuration_index)] = ...
            summarize_with_ci(recovery_values(valid), ...
            bootstrap_resamples, ci_level, ...
            300000 + configuration_index);
        [FinalMeanNRE100Mean(configuration_index), ...
            FinalMeanNRE100Std(configuration_index), ...
            FinalMeanNRE100CILower(configuration_index), ...
            FinalMeanNRE100CIUpper(configuration_index)] = ...
            summarize_with_ci(final_values(valid), ...
            bootstrap_resamples, ci_level, ...
            310000 + configuration_index);

        paired = valid & default_valid & ...
            isfinite(recovery_values) & isfinite(default_recovery) & ...
            isfinite(final_values) & isfinite(default_final);
        PairedRuns(configuration_index) = nnz(paired);

        recovery_difference = ...
            recovery_values(paired) - default_recovery(paired);
        final_difference = final_values(paired) - default_final(paired);
        [RecoveryIntegral50DifferenceMean(configuration_index), ...
            RecoveryIntegral50DifferenceCILower(configuration_index), ...
            RecoveryIntegral50DifferenceCIUpper(configuration_index)] = ...
            summarize_difference(recovery_difference, ...
            bootstrap_resamples, ci_level, ...
            320000 + configuration_index);
        [FinalMeanNRE100DifferenceMean(configuration_index), ...
            FinalMeanNRE100DifferenceCILower(configuration_index), ...
            FinalMeanNRE100DifferenceCIUpper(configuration_index)] = ...
            summarize_difference(final_difference, ...
            bootstrap_resamples, ci_level, ...
            330000 + configuration_index);

        runtime_values = state.runtime_seconds( ...
            configuration_index, valid);
        RuntimeMedianSeconds(configuration_index) = ...
            finite_median(runtime_values);
        RuntimeIQRSeconds(configuration_index) = ...
            finite_iqr(runtime_values);
        MeanLambdaMean(configuration_index) = finite_mean(reshape( ...
            state.metrics(configuration_index, valid, ...
            metric_index('MeanLambda')), [], 1));
        MinimumLambdaPost50Mean(configuration_index) = ...
            finite_mean(reshape(state.metrics( ...
            configuration_index, valid, ...
            metric_index('MinimumLambdaPost50')), [], 1));
        MeanPriorIRLSIterationsMean(configuration_index) = ...
            finite_mean(reshape(state.metrics( ...
            configuration_index, valid, ...
            metric_index('MeanPriorIRLSIterations')), [], 1));
        MeanPosteriorIRLSIterationsMean(configuration_index) = ...
            finite_mean(reshape(state.metrics( ...
            configuration_index, valid, ...
            metric_index('MeanPosteriorIRLSIterations')), [], 1));
        HuberDeltaMean(configuration_index) = finite_mean( ...
            state.huber_delta(configuration_index, valid));
        SideThresholdMean(configuration_index) = finite_mean( ...
            state.side_threshold(configuration_index, valid));
    end

    summary_table = table( ...
        ConfigurationID, Label, ParameterFamily, ParameterValue, ...
        SuccessfulRuns, FailedRuns, PairedRuns, ...
        PreMutationMeanNRE50Mean, ...
        RecoveryIntegral50Mean, RecoveryIntegral50Std, ...
        RecoveryIntegral50CILower, RecoveryIntegral50CIUpper, ...
        RecoveryIntegral50DifferenceMean, ...
        RecoveryIntegral50DifferenceCILower, ...
        RecoveryIntegral50DifferenceCIUpper, ...
        FinalMeanNRE100Mean, FinalMeanNRE100Std, ...
        FinalMeanNRE100CILower, FinalMeanNRE100CIUpper, ...
        FinalMeanNRE100DifferenceMean, ...
        FinalMeanNRE100DifferenceCILower, ...
        FinalMeanNRE100DifferenceCIUpper, ...
        RuntimeMedianSeconds, RuntimeIQRSeconds, ...
        MeanLambdaMean, MinimumLambdaPost50Mean, ...
        MeanPriorIRLSIterationsMean, ...
        MeanPosteriorIRLSIterationsMean, ...
        HuberDeltaMean, SideThresholdMean);
end

function [mean_value, std_value, lower, upper] = ...
    summarize_with_ci(values, num_resamples, ci_level, seed)

    values = values(isfinite(values));
    if isempty(values)
        mean_value = NaN;
        std_value = NaN;
        lower = NaN;
        upper = NaN;
        return;
    end
    mean_value = mean(values);
    std_value = std(values, 0);
    [lower, upper] = bootstrap_mean_ci( ...
        values, num_resamples, ci_level, seed);
end

function [mean_value, lower, upper] = summarize_difference( ...
    values, num_resamples, ci_level, seed)

    values = values(isfinite(values));
    if isempty(values)
        mean_value = NaN;
        lower = NaN;
        upper = NaN;
        return;
    end
    mean_value = mean(values);
    [lower, upper] = bootstrap_mean_ci( ...
        values, num_resamples, ci_level, seed);
end

function [lower, upper] = bootstrap_mean_ci( ...
    values, num_resamples, ci_level, seed)

    values = values(:);
    if numel(values) < 2
        lower = NaN;
        upper = NaN;
        return;
    end

    stream = RandStream('mt19937ar', 'Seed', seed);
    indices = randi( ...
        stream, numel(values), numel(values), num_resamples);
    bootstrap_means = sort(mean(values(indices), 1));
    tail = (1 - ci_level) / 2;
    lower = linear_quantile(bootstrap_means, tail);
    upper = linear_quantile(bootstrap_means, 1 - tail);
end

function value = finite_mean(values)
    values = values(isfinite(values));
    if isempty(values)
        value = NaN;
    else
        value = mean(values);
    end
end

function value = finite_median(values)
    values = values(isfinite(values));
    if isempty(values)
        value = NaN;
    else
        value = median(values);
    end
end

function value = finite_iqr(values)
    values = sort(values(isfinite(values)));
    if isempty(values)
        value = NaN;
    else
        value = linear_quantile(values, 0.75) - ...
            linear_quantile(values, 0.25);
    end
end

function value = linear_quantile(sorted_values, probability)
    sorted_values = sorted_values(:);
    position = 1 + (numel(sorted_values) - 1) * probability;
    lower_index = floor(position);
    upper_index = ceil(position);
    if lower_index == upper_index
        value = sorted_values(lower_index);
    else
        weight = position - lower_index;
        value = sorted_values(lower_index) + weight * ...
            (sorted_values(upper_index) - sorted_values(lower_index));
    end
end

function failure_table = build_failure_table(failure_records)
    if isempty(failure_records)
        failure_table = table( ...
            zeros(0, 1), zeros(0, 1), cell(0, 1), ...
            cell(0, 1), cell(0, 1), ...
            'VariableNames', {'Trial', 'TrialSeed', ...
            'ConfigurationID', 'Identifier', 'Message'});
    else
        failure_table = struct2table(failure_records);
    end
end

function plot_s6_metric(summary_table, configurations, metric_name, ...
    y_label, file_name, result_dir, export_results)

    families = {'lambda_min', 'lambda_max', 'huber', 'alpha', ...
        'theta', 'mu', 'rank', 'irls'};
    family_titles = {'$\lambda_{\min}$', '$\lambda_{\max}$', ...
        'Huber multiplier', '$\alpha$', 'Dead-zone multiplier', ...
        '$\mu$', 'Estimated rank', 'IRLS iterations'};
    mean_values = summary_table.([metric_name, 'Mean']);
    lower_values = summary_table.([metric_name, 'CILower']);
    upper_values = summary_table.([metric_name, 'CIUpper']);
    default_index = find(strcmp({configurations.id}, 'default'), 1);

    figure_handle = figure( ...
        'Color', 'w', 'Visible', 'off', ...
        'Position', [80, 80, 1500, 720]);

    for family_index = 1:numel(families)
        family = families{family_index};
        axes_handle = subplot(2, 4, family_index, ...
            'Parent', figure_handle);
        hold(axes_handle, 'on');
        box(axes_handle, 'on');
        grid(axes_handle, 'on');

        family_indices = find(strcmp( ...
            {configurations.parameter_family}, family));
        configuration_indices = [default_index, family_indices];
        parameter_axis = zeros(size(configuration_indices));
        for value_index = 1:numel(configuration_indices)
            parameter_axis(value_index) = family_parameter_value( ...
                configurations(configuration_indices(value_index)), ...
                family);
        end
        [parameter_axis, order] = sort(parameter_axis);
        configuration_indices = configuration_indices(order);

        plotted_means = mean_values(configuration_indices);
        lower_errors = plotted_means - ...
            lower_values(configuration_indices);
        upper_errors = upper_values(configuration_indices) - ...
            plotted_means;
        errorbar(axes_handle, parameter_axis, plotted_means, ...
            lower_errors, upper_errors, '-o', ...
            'Color', [0.15, 0.40, 0.70], ...
            'MarkerFaceColor', [0.15, 0.40, 0.70], ...
            'LineWidth', 1.3, 'MarkerSize', 6, 'CapSize', 7);

        default_x = family_parameter_value( ...
            configurations(default_index), family);
        plot(axes_handle, default_x, mean_values(default_index), ...
            's', 'Color', [0.75, 0.20, 0.15], ...
            'MarkerFaceColor', [0.75, 0.20, 0.15], ...
            'MarkerSize', 7);

        if strcmp(family, 'mu')
            set(axes_handle, 'XScale', 'log');
        end
        title(axes_handle, family_titles{family_index}, ...
            'Interpreter', 'latex');
        xlabel(axes_handle, 'Parameter value');
        ylabel(axes_handle, y_label);
        set(axes_handle, ...
            'FontName', 'Times New Roman', 'FontSize', 10);
    end

    if export_results
        set(figure_handle, 'Visible', 'on');
        savefig(figure_handle, fullfile(result_dir, [file_name, '.fig']));
        set(figure_handle, 'Visible', 'off');
        set(figure_handle, 'Units', 'Inches');
        position = get(figure_handle, 'Position');
        set(figure_handle, ...
            'PaperPositionMode', 'auto', ...
            'PaperUnits', 'Inches', ...
            'PaperSize', [position(3), position(4)]);
        print(figure_handle, fullfile(result_dir, [file_name, '.pdf']), ...
            '-dpdf', '-vector');
        print(figure_handle, fullfile(result_dir, [file_name, '.eps']), ...
            '-depsc', '-vector');
    end
    close(figure_handle);
end

function value = family_parameter_value(configuration, family)
    switch family
        case 'lambda_min'
            value = configuration.lambda_min;
        case 'lambda_max'
            value = configuration.lambda_max;
        case 'huber'
            value = configuration.huber_scale_multiplier;
        case 'alpha'
            value = configuration.grad_ema_alpha;
        case 'theta'
            value = configuration.side_threshold_multiplier;
        case 'mu'
            value = configuration.mu;
        case 'rank'
            value = configuration.estimated_rank;
        case 'irls'
            value = configuration.irls_max_iters;
        otherwise
            error('Exp_S6:UnknownParameterFamily', ...
                'Unknown parameter family: %s.', family);
    end
end
